# fish shell abbreviations

# git
abbr -a ga 'git add'
abbr -a ga. 'git add .'
abbr -a gaa 'git add --all'
abbr -a gp 'git push'
abbr -a gpf 'git push --force'
abbr -a gc 'git commit'
abbr -a gcm 'git commit -m'
abbr -a gca 'git commit --amend'
abbr -a gca! 'git commit --amend --no-edit'
abbr -a gco 'git checkout'
abbr -a gcob 'git checkout -b'
abbr -a gb 'git branch'
abbr -a gbd 'git branch -d'
abbr -a gs 'git status'
abbr -a gpl 'git pull'
abbr -a gl 'git log'
abbr -a gd 'git diff'
abbr -a g 'git'
